/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.NuevaCuenta;
import Vistas.Principal.*;
import Vistas.InicioSeccion.inicioSeccionC;
import Vistas.info.InfoC;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Emml_
 */
public class CrearCuentaC extends javax.swing.JFrame {
Conexion conecion = new Conexion();
    Connection cin = conecion.Entrar();
    PreparedStatement ps;
    public CrearCuentaC() {
        initComponents();
        CrearCuentaC.this.setBackground(new Color(0, 0, 0, 0));
    }
    void Registrar(){
        
        String insertar = "insert into Conductores (Nombre,Apellidos,NumCel,PassW,Correo,Ciudad,Estado)values (?,?,?,?,?,?,?)";
        try {
            ps = cin.prepareCall(insertar);
            ps.setString(1, Nombre.getText());
            ps.setString(2, Apellidos.getText());
            ps.setString(3, NumCel.getText());
            ps.setString(4, PassW.getText());
            ps.setString(5, Correo.getText());
            ps.setString(6, Ciudad.getText());
            ps.setString(7, Estado.getText());
           
            int registro = ps.executeUpdate();
            
            if(registro > 0){
                JOptionPane.showMessageDialog(this, "Usuario registrado con exito", "Bien", JOptionPane.QUESTION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,"El usuario no se registro con exito", "Atencion", JOptionPane.ERROR_MESSAGE);
            }
        } catch(Exception E){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        Nombre = new LIB.JTexfieldPH_FielTex();
        Apellidos = new LIB.JTexfieldPH_FielTex();
        Correo = new LIB.JTexfieldPH_FielTex();
        PassW = new LIB.JTexfieldPH_FielTex();
        NumCel = new LIB.JTexfieldPH_FielTex();
        Ciudad = new LIB.JTexfieldPH_FielTex();
        Estado = new LIB.JTexfieldPH_FielTex();
        jButton1 = new javax.swing.JButton();
        fSGradientPanel1 = new LIB.FSGradientPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Uber");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 210, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Back.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Tengo Auto");
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jCheckBox2.setText("Necesito un auto");
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 130, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Registrate ahora");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 230, -1));

        Nombre.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Nombre.setPlaceholder("Nombre");
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel2.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 220, -1));

        Apellidos.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Apellidos.setPlaceholder("Apellidos");
        Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosActionPerformed(evt);
            }
        });
        jPanel2.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 220, -1));

        Correo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Correo.setPlaceholder("Correo");
        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        jPanel2.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, -1));

        PassW.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        PassW.setPlaceholder("Contraseña");
        PassW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassWActionPerformed(evt);
            }
        });
        jPanel2.add(PassW, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 220, -1));

        NumCel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        NumCel.setPlaceholder("Numero celular");
        NumCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCelActionPerformed(evt);
            }
        });
        jPanel2.add(NumCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 220, -1));

        Ciudad.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Ciudad.setPlaceholder("Ciudad");
        Ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiudadActionPerformed(evt);
            }
        });
        jPanel2.add(Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, -1));

        Estado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Estado.setPlaceholder("Estado");
        jPanel2.add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 110, -1));

        jButton1.setBackground(new java.awt.Color(18, 18, 18));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Siguiente");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 200, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 300, 390));

        fSGradientPanel1.setFSEndColor(new java.awt.Color(18, 18, 18));
        fSGradientPanel1.setFSGradientFocus(100);
        fSGradientPanel1.setFSStartColor(new java.awt.Color(9, 9, 26));
        fSGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/close.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        fSGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        getContentPane().add(fSGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 0, 303, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        inicioSeccionC isc = new inicioSeccionC();
        isc.show();
        
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Registrar();
        InfoC ic = new InfoC();
        ic.show();
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidosActionPerformed

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void PassWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassWActionPerformed

    private void NumCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumCelActionPerformed

    private void CiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuentaC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuentaC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.JTexfieldPH_FielTex Apellidos;
    private LIB.JTexfieldPH_FielTex Ciudad;
    private LIB.JTexfieldPH_FielTex Correo;
    private LIB.JTexfieldPH_FielTex Estado;
    private LIB.JTexfieldPH_FielTex Nombre;
    private LIB.JTexfieldPH_FielTex NumCel;
    private LIB.JTexfieldPH_FielTex PassW;
    private LIB.FSGradientPanel fSGradientPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
